name: peka
channels:
    - anaconda
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - python=3.7
    - matplotlib=3.1.2
    - numpy=1.17.4
    - pybedtools=0.8.0
    - scipy=1.3.1
    - seaborn=0.9.0
    - plumbum=1.6.8
    - scikit-learn=0.21.3
    - pandas=0.24.2
    - textdistance=4.1.3